// Generated by gencpp from file recog/clouds.msg
// DO NOT EDIT!


#ifndef RECOG_MESSAGE_CLOUDS_H
#define RECOG_MESSAGE_CLOUDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/PointCloud2.h>

namespace recog
{
template <class ContainerAllocator>
struct clouds_
{
  typedef clouds_<ContainerAllocator> Type;

  clouds_()
    : clouds()  {
    }
  clouds_(const ContainerAllocator& _alloc)
    : clouds(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::sensor_msgs::PointCloud2_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::other >  _clouds_type;
  _clouds_type clouds;





  typedef boost::shared_ptr< ::recog::clouds_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::recog::clouds_<ContainerAllocator> const> ConstPtr;

}; // struct clouds_

typedef ::recog::clouds_<std::allocator<void> > clouds;

typedef boost::shared_ptr< ::recog::clouds > cloudsPtr;
typedef boost::shared_ptr< ::recog::clouds const> cloudsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::recog::clouds_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::recog::clouds_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::recog::clouds_<ContainerAllocator1> & lhs, const ::recog::clouds_<ContainerAllocator2> & rhs)
{
  return lhs.clouds == rhs.clouds;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::recog::clouds_<ContainerAllocator1> & lhs, const ::recog::clouds_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace recog

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::recog::clouds_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::recog::clouds_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::recog::clouds_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::recog::clouds_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::recog::clouds_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::recog::clouds_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::recog::clouds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a1ae9b373e3c6d99d77b25f8b07122a1";
  }

  static const char* value(const ::recog::clouds_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa1ae9b373e3c6d99ULL;
  static const uint64_t static_value2 = 0xd77b25f8b07122a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::recog::clouds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "recog/clouds";
  }

  static const char* value(const ::recog::clouds_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::recog::clouds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/PointCloud2[] clouds\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
;
  }

  static const char* value(const ::recog::clouds_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::recog::clouds_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.clouds);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct clouds_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::recog::clouds_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::recog::clouds_<ContainerAllocator>& v)
  {
    s << indent << "clouds[]" << std::endl;
    for (size_t i = 0; i < v.clouds.size(); ++i)
    {
      s << indent << "  clouds[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "    ", v.clouds[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RECOG_MESSAGE_CLOUDS_H
