// Generated by gencpp from file recog/Position.msg
// DO NOT EDIT!


#ifndef RECOG_MESSAGE_POSITION_H
#define RECOG_MESSAGE_POSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace recog
{
template <class ContainerAllocator>
struct Position_
{
  typedef Position_<ContainerAllocator> Type;

  Position_()
    : pitch(0.0)
    , yaw(0.0)
    , distance(0.0)  {
    }
  Position_(const ContainerAllocator& _alloc)
    : pitch(0.0)
    , yaw(0.0)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::recog::Position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::recog::Position_<ContainerAllocator> const> ConstPtr;

}; // struct Position_

typedef ::recog::Position_<std::allocator<void> > Position;

typedef boost::shared_ptr< ::recog::Position > PositionPtr;
typedef boost::shared_ptr< ::recog::Position const> PositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::recog::Position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::recog::Position_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::recog::Position_<ContainerAllocator1> & lhs, const ::recog::Position_<ContainerAllocator2> & rhs)
{
  return lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::recog::Position_<ContainerAllocator1> & lhs, const ::recog::Position_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace recog

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::recog::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::recog::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::recog::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::recog::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::recog::Position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::recog::Position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::recog::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad823f8c25b65aa56498330a08801ed1";
  }

  static const char* value(const ::recog::Position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad823f8c25b65aa5ULL;
  static const uint64_t static_value2 = 0x6498330a08801ed1ULL;
};

template<class ContainerAllocator>
struct DataType< ::recog::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "recog/Position";
  }

  static const char* value(const ::recog::Position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::recog::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pitch\n"
"float32 yaw\n"
"float32 distance\n"
;
  }

  static const char* value(const ::recog::Position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::recog::Position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::recog::Position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::recog::Position_<ContainerAllocator>& v)
  {
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RECOG_MESSAGE_POSITION_H
